/**
 * activeOverrides stub — all overrides disabled.
 */
export const activeOverrides = {
  STARTING_MONEY_OVERRIDE: 0,
  STARTING_LEVEL_OVERRIDE: 0,
  STARTING_BIOME_OVERRIDE: null,
  OPP_SPECIES_OVERRIDE: 0,
  ABILITY_OVERRIDE: 0,
  OPP_ABILITY_OVERRIDE: 0,
  MOVE_OVERRIDE: 0,
  OPP_MOVE_OVERRIDE: 0,
  SHINY_OVERRIDE: false,
  OPP_SHINY_OVERRIDE: false,
  ITEM_REWARD_OVERRIDE: [] as any[],
  STARTER_SPECIES_OVERRIDE: 0,
  WEATHER_OVERRIDE: 0,
  NEVER_CRIT_OVERRIDE: false,
  OPP_PASSIVE_ABILITY_OVERRIDE: 0,
};
